<?php

declare(strict_types=1);

/**
 * Incident-scoped storage boundary for the legacy single-message PDFs.
 *
 * Message numbers restart for every incident. The incident ID is therefore a
 * mandatory part of every generated filename and every list/download check is
 * bound to the currently active incident.
 */

require_once __DIR__ . '/file_access.php';
require_once __DIR__ . '/incident.php';

function estab_generated_form_database_name(string $database): string
{
    if (preg_match('/\A[A-Za-z0-9_]{1,64}\z/D', $database) !== 1) {
        throw new InvalidArgumentException('Invalid generated-form database name');
    }
    return $database;
}

function estab_generated_form_direction(mixed $value): string
{
    if (!is_string($value) || !in_array($value, ['E', 'A'], true)) {
        throw new InvalidArgumentException('Invalid generated-form direction');
    }
    return $value;
}

function estab_generated_form_number(mixed $value): int
{
    try {
        return estab_incident_positive_id($value, 'Nachrichtennummer');
    } catch (EstabIncidentInputException $exception) {
        throw new InvalidArgumentException(
            'Invalid generated-form message number',
            0,
            $exception
        );
    }
}

/** Build the collision-free basename persisted in the shared data volume. */
function estab_generated_form_filename(
    string $database,
    mixed $incidentId,
    mixed $number,
    mixed $direction
): string {
    $filename = sprintf(
        '%s Einsatz-%d %d %s.pdf',
        estab_generated_form_database_name($database),
        estab_incident_positive_id($incidentId),
        estab_generated_form_number($number),
        estab_generated_form_direction($direction)
    );
    return estab_file_validate_name('vordruck', $filename);
}

/**
 * Parse only the canonical filename generated by this application.
 *
 * @return array{incident_id:int,number:int,direction:string}
 */
function estab_generated_form_parse_filename(
    string $database,
    string $filename
): array {
    $database = estab_generated_form_database_name($database);
    $filename = estab_file_validate_name('vordruck', $filename);
    $pattern = '/\A' . preg_quote($database, '/')
        . ' Einsatz-([1-9][0-9]*) ([1-9][0-9]*) ([EA])\.pdf\z/D';
    if (preg_match($pattern, $filename, $parts) !== 1) {
        throw new InvalidArgumentException('Invalid incident-scoped form filename');
    }
    return [
        'incident_id' => estab_incident_positive_id($parts[1]),
        'number' => estab_generated_form_number($parts[2]),
        'direction' => estab_generated_form_direction($parts[3]),
    ];
}

/**
 * Publish a complete PDF atomically in the persistent generated-form area.
 *
 * The temporary file is created on the same filesystem. A failed generation
 * therefore never replaces the previously complete document with a partial
 * byte sequence.
 */
function estab_generated_form_publish(
    string $root,
    string $filename,
    string $document
): string {
    $filename = estab_file_validate_name('vordruck', $filename);
    if (!str_starts_with($document, '%PDF-') || !str_ends_with($document, "%%EOF\n")) {
        throw new RuntimeException('Generated document is not a complete PDF');
    }
    $resolvedRoot = realpath($root);
    if ($resolvedRoot === false || !is_dir($resolvedRoot) || !is_writable($resolvedRoot)) {
        throw new RuntimeException('Generated-form area is unavailable');
    }

    $temporary = tempnam($resolvedRoot, '.estab-vordruck-');
    if (!is_string($temporary) || $temporary === '') {
        throw new RuntimeException('Could not reserve generated-form file');
    }
    try {
        $written = file_put_contents($temporary, $document, LOCK_EX);
        if ($written !== strlen($document)) {
            throw new RuntimeException('Could not persist complete generated form');
        }
        if (!chmod($temporary, 0660)) {
            throw new RuntimeException('Could not protect generated form');
        }
        $target = $resolvedRoot . DIRECTORY_SEPARATOR . $filename;
        if (!rename($temporary, $target)) {
            throw new RuntimeException('Could not publish generated form');
        }
        $temporary = '';
        return $target;
    } finally {
        if ($temporary !== '' && is_file($temporary)) {
            unlink($temporary);
        }
    }
}

/**
 * Lock pending, completed messages belonging to one authoritative incident.
 *
 * @return list<array<string,mixed>>
 */
function estab_generated_form_fetch_pending(
    mysqli $connection,
    string $messageTable,
    int $incidentId,
    int $limit
): array {
    $incidentId = estab_incident_positive_id($incidentId);
    if ($limit < 1 || $limit > 1000) {
        throw new InvalidArgumentException('Invalid generated-form batch size');
    }
    $statement = $connection->prepare(
        'SELECT * FROM ' . estab_auth_table($messageTable)
        . " WHERE `einsatz_id` = ? AND `x04_druck` = 'f'"
        . " AND `x01_abschluss` = 't'"
        . ' ORDER BY `00_lfd` LIMIT ? FOR UPDATE'
    );
    if (!$statement) {
        throw new RuntimeException('Could not prepare generated-form queue');
    }
    try {
        $statement->bind_param('ii', $incidentId, $limit);
        if (!$statement->execute()) {
            throw new RuntimeException('Could not read generated-form queue');
        }
        $result = $statement->get_result();
        $rows = $result->fetch_all(MYSQLI_ASSOC);
        $result->free();
        return is_array($rows) ? array_values($rows) : [];
    } finally {
        $statement->close();
    }
}

/** Mark exactly the just-published active-incident message as printed. */
function estab_generated_form_mark_published(
    mysqli $connection,
    string $messageTable,
    int $incidentId,
    mixed $messageId
): void {
    $incidentId = estab_incident_positive_id($incidentId);
    $messageId = estab_incident_positive_id($messageId, 'Nachrichten-ID');
    $statement = $connection->prepare(
        'UPDATE ' . estab_auth_table($messageTable)
        . " SET `x04_druck` = 't', `x05_druck_d` = NOW()"
        . " WHERE `00_lfd` = ? AND `einsatz_id` = ?"
        . " AND `x04_druck` = 'f' AND `x01_abschluss` = 't'"
    );
    if (!$statement) {
        throw new RuntimeException('Could not prepare generated-form state update');
    }
    try {
        $statement->bind_param('ii', $messageId, $incidentId);
        if (!$statement->execute() || $statement->affected_rows !== 1) {
            throw new RuntimeException('Generated-form message changed concurrently');
        }
    } finally {
        $statement->close();
    }
}

/**
 * Return only real files backed by printed rows of the active incident.
 *
 * @return list<array{
 *   name:string,size:int,modified:int,message_id:int,number:int,direction:string
 * }>
 */
function estab_generated_form_list_active(
    mysqli $connection,
    string $messageTable,
    string $database,
    string $root
): array {
    $incident = estab_incident_require_active($connection);
    $incidentId = (int) $incident['active_einsatz_id'];
    $statement = $connection->prepare(
        'SELECT `00_lfd`, `04_nummer`, `04_richtung` FROM '
        . estab_auth_table($messageTable)
        . " WHERE `einsatz_id` = ? AND `x04_druck` = 't'"
        . " AND `x01_abschluss` = 't'"
        . ' ORDER BY `04_richtung`, `04_nummer` DESC, `00_lfd` DESC'
    );
    if (!$statement) {
        throw new RuntimeException('Could not prepare active generated-form list');
    }
    try {
        $statement->bind_param('i', $incidentId);
        if (!$statement->execute()) {
            throw new RuntimeException('Could not read active generated forms');
        }
        $result = $statement->get_result();
        $rows = $result->fetch_all(MYSQLI_ASSOC);
        $result->free();
    } finally {
        $statement->close();
    }

    $files = [];
    foreach ($rows as $row) {
        try {
            $filename = estab_generated_form_filename(
                $database,
                $incidentId,
                $row['04_nummer'] ?? null,
                $row['04_richtung'] ?? null
            );
            $path = estab_file_resolve($root, 'vordruck', $filename);
            $size = filesize($path);
            $modified = filemtime($path);
            if ($size === false || $modified === false) {
                continue;
            }
            $files[] = [
                'name' => $filename,
                'size' => max(0, (int) $size),
                'modified' => max(0, (int) $modified),
                'message_id' => estab_incident_positive_id(
                    $row['00_lfd'] ?? null,
                    'Nachrichten-ID'
                ),
                'number' => estab_generated_form_number(
                    $row['04_nummer'] ?? null
                ),
                'direction' => estab_generated_form_direction(
                    $row['04_richtung'] ?? null
                ),
            ];
        } catch (InvalidArgumentException | RuntimeException) {
            // A stale, partial or foreign file never becomes downloadable.
            continue;
        }
    }
    return $files;
}

/** Prove that a requested generated form belongs to the active incident. */
function estab_generated_form_require_active(
    mysqli $connection,
    string $messageTable,
    string $database,
    string $filename,
    bool $forUpdate = false
): array {
    $parsed = estab_generated_form_parse_filename($database, $filename);
    $incident = estab_incident_require_active($connection, $forUpdate);
    $incidentId = (int) $incident['active_einsatz_id'];
    if ($parsed['incident_id'] !== $incidentId) {
        throw new EstabIncidentNotFoundException(
            'Generated form does not belong to the active incident'
        );
    }

    $statement = $connection->prepare(
        'SELECT `00_lfd` FROM ' . estab_auth_table($messageTable)
        . " WHERE `einsatz_id` = ? AND `04_nummer` = ?"
        . " AND `04_richtung` = ? AND `x04_druck` = 't'"
        . " AND `x01_abschluss` = 't' LIMIT 1"
    );
    if (!$statement) {
        throw new RuntimeException('Could not prepare generated-form authorization');
    }
    try {
        $statement->bind_param(
            'iis',
            $incidentId,
            $parsed['number'],
            $parsed['direction']
        );
        if (!$statement->execute()) {
            throw new RuntimeException('Could not authorize generated form');
        }
        $result = $statement->get_result();
        $row = $result->fetch_assoc();
        $result->free();
    } finally {
        $statement->close();
    }
    if (!is_array($row)) {
        throw new EstabIncidentNotFoundException(
            'Generated form is not backed by an active message'
        );
    }
    return [
        'incident_id' => $incidentId,
        'message_id' => estab_incident_positive_id(
            $row['00_lfd'] ?? null,
            'Nachrichten-ID'
        ),
        'number' => $parsed['number'],
        'direction' => $parsed['direction'],
    ];
}
