FROM mariadb:11.8.8

COPY docker/db/migrate.sh /usr/local/bin/estab-migrate
COPY docker/db/migrations/ /opt/estab/migrations/
COPY docker/db/verify.sql /opt/estab/verify.sql

RUN chmod 0755 /usr/local/bin/estab-migrate \
    && find /opt/estab -type f -name '*.sql' -exec chmod 0444 '{}' +

ENTRYPOINT ["/usr/local/bin/estab-migrate"]
